### ISSUE TITLE
Can't find generated file

### ISSUE THREAD

**Issue by anche** [elidickinson/php-export-data#1]
I tried to use the 'file' stream to generate the file.  But I can't find the file after it completed.  Where is the default folder the file should save to?  I run the script in the /var/www/html/ folder on Amazon EC2 instance.  

Thank you!

**Comment by elidickinson** [comment]
Greetings,

I think PHP defaults to whatever directory the first PHP script is run from, but it may depend on your server configuration. There's an easy solution, though: if you want it in a particular place, pass a full path like "/var/www/html/myfile.csv" Does that solve your problem?

**Comment by elidickinson** [comment]
I assume you've figured this out? If not, please reopen the issue
