### ISSUE TITLE
Warning Excel

### ISSUE THREAD

**Issue by Mauricio32** [elidickinson/php-export-data#10]
Hello,
When you open a file in Excel 2007, you receives a notice that the file format differs from the format that specifies the file extension, this is a message security standard Excel, is there any way within the class you created, not display this message?

Thank you in advance!
And congratulations on the good work ...

**Comment by mcouillard** [comment]
What extension did you save the file as? It's been said only XML won't give such a warning, any other extension will.

**Comment by Mauricio32** [comment]
The extension to which the file is being generated XLS, using this extension does not have a way to not display this warning?

Thank you in advance!

**Comment by elidickinson** [comment]
@Mauricio32 Unfortunately I don't think that's possible with this library. Excel 2007 will complain about any .XLS file that isn't actually in XLS format even if it's in a different format that Excel knows how to read (which is what we're generating here).

If that's a dealbreaker for you, you may need to investigate another solution that generate real XLS files. Unfortunately I think the good ones aren't fully open source.

**Comment by Mauricio32** [comment]
Thank you, I will analyze some alternatives to this problem.

Again, congratulations on the great job!

**Comment by elidickinson** [comment]
Cool, thanks. If you discover anything interesting, come back and post a comment. I'm sure other people have the same question.
