### ISSUE TITLE
UTF-8 characters are not displayed - export CSV ::::  ç, à ,l',é

### ISSUE THREAD

**Issue by thanagit** [elidickinson/php-export-data#13]
Hi,
Trying to export CSV file with UTF- 8 characers(Eg: ç, à ,é) is not working. Below is the format currently its rendering in CSV file. Can you please share your ideas.
 ç => Ã§
à   => Ã  
é  => Ã©

**Comment by elidickinson** [comment]
Could you create a small test script that demonstrates the problem? Is it possible the page you're looking at has a different character set defined and that's mucking it up?

**Comment by thanagit** [comment]
Hi Dickinson,

Thanks for your  reply. In the mean while i have used  mb_convert_encoding function to display the UTF-8 characters to display in CSV.

Eg:
$exporter = new ExportDataCSV('browser', "export-" . date("d-m-Y") . ".csv");
 $exporter->initialize();
  $keys = array(
    t('Date'),
    t('UFT-8 Data')
 );
 $exporter->addRow($keys);
 $date = date("d-m-Y");
 $data ="reçoit";  // OLD Code
 $data = mb_convert_encoding($data, 'UTF-16LE', 'UTF-8'); // NEW CODE
 $output = array($date, $data);
 $exporter->addRow($output);
 $exporter->finalize();
