### ISSUE TITLE
Floats are not detected as numbers

### ISSUE THREAD

**Issue by andrespoder** [elidickinson/php-export-data#3]
check comment here:
https://github.com/elidickinson/php-export-data/commit/43caa9880889c91ca840e637c0931d38cbcf21b8

**Comment by elidickinson** [comment]
Good question. I think there was an issue with some version of Excel doing something I didn't like with floating point numbers formated as Number, but I can't quite see the problem right now.

If you switch it to is_numeric or something similar, I would be curious to hear how it works in Excel in practice.

**Comment by andrespoder** [comment]
I forked your project and switched to is_numeric. I'll let you know what are the results :) Seems that there is no problems in newer versions of excel/openoffice/libreoffice, but we havent tested with older versions yet.

**Comment by elidickinson** [comment]
Hmm, cool. Seems fine to me too. 

The one thing I might suggest is using preg_match("/^\d+(.\d*)?$/",$item) instead of is_numeric() just because is_numeric will treat "0xf" and "3e5" as numbers, which may lead to some rare, weird problems.

**Comment by glensc** [comment]
don't forget negative numbers, and decimals separator as comma! :)

**Comment by glensc** [comment]
```
/^-?\d+(?:[.,]\d+)?$/
```
- optional minus
- numbers 1 to many
- start non capturing group
- match dot or comma
- match numbers, one to many
- end optional group

:)

and if you don't want to accept comma (leave dot to comma translation to application):

```
/^-?\d+(?:\.\d+)?$/
```

you forgot to escape dot in your original expression, and it allows numbers like "10." which imho is wrong

and now thinking the leading decimal could also be optional, as "-.009" is valid float!

so, final regexp:

```
/^-?\d*(?:[.,]\d+)?$/
```

**Comment by elidickinson** [comment]
The other catch is that Excel will round numbers after roughly 15 digits. This is not so great if the field you're outputting is, say, a 20 digit product ID number. I suppose it's a judgement call, but in that case I'd almost always want the field outputted as text rather than suffer a loss of precision.

**Comment by elidickinson** [comment]
I'm about to commit a fix for this.

Thanks for the regex, @glensc. I tweaked it to require at least one leading digit (right now "-" is treated as a number) as well as to only treat strings of length 15 or less as numbers. This isn't quite 100% right, but it errs on the side of conservatism (mistakenly treating text as numbers is worse than the opposite)

**Comment by glensc** [comment]
```
if(preg_match("/^-?\d+(?:[.,]\d+)?$/",$item) && (strlen($item) < 15)) {
```

if you worry about precision, limit the length after the decimal separator, not whole number:

```
/^-?\d+(?:[.,]\d{1,15})?$/
```

also you are then not allowing ".9" or "-.9", for that i do not have good idea how to fit to single regex without making regexp totally unreadable. not sure is that relevant in real world, as padding with zero is quite easy  :)

**Comment by elidickinson** [comment]
No, it only stores 15 digits of precision, not 15 decimal places. 12345678901234567890 becomes 12345678901234600000

**Comment by mekarorogerio** [comment]
I couldn't open a xls on Numbers-MacOS, but on LibreOffice I could. How to resolve this ?
