### ISSUE TITLE
Download option for exportated data

### ISSUE THREAD

**Issue by rahuljha088** [elidickinson/php-export-data#6]
Hi elidickinson ,

i am trying to get the automatic file download option after executing the script. but, it is not working. 
header('Content-Type: application/vnd.ms-excel');
header("Content-Disposition: attachment;filename=$Matched");
header('Cache-Control: max-age=0');

i tried by putting this in the test_big_excel_file.php but it is not working. 
Help me.

Thanks

**Comment by elidickinson** [comment]
Hello,

Could you be more specific? What do you think should happen and what is happening instead?

**Comment by rahuljha088** [comment]
When i execute the test_big_excel_file.php script, it creates an excel file in the same directory where this script is. what i want is to get the "save as" option instead of automatically downloaded into the directory. and one more thing the file type is in XML . so can i change this file type into xls using any php code.

**Comment by greenweb** [comment]
rahuljha088 you could export as a string and then save that into a file that you determine the location and file name of.

**Comment by elidickinson** [comment]
Hi rahuljha088,

Simply change the line `$excel = new ExportDataExcel('file');` to `$excel = new ExportDataExcel('browser');` and it will stream to the browser instead of saving.
