### ISSUE TITLE
Die script after finalize()

### ISSUE THREAD

**Issue by subdesign** [elidickinson/php-export-data#7]
If I don't use die() after the finalize() method, all my html content will be added at the end of the xls file. It's a recommendation only.  thanks

EDIT: sorry I didn't see the exit() in the readme file, I only watched the source code.

**Comment by elidickinson** [comment]
No problem. It's a good point.

Personally, I try to set up my code so that PHP files are either 100% PHP code with no HTML, or (almost) all HTML, with PHP only used to print variables and manipulate the formatting.
